name: new_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5

  # Navigation
  go_router: ^13.0.1

  # UI
  cupertino_icons: ^1.0.6

  # Local storage
  shared_preferences: ^2.2.2

  flutter_dotenv: ^5.1.0
  get_it: ^7.6.4
  http: ^1.0.0
  dio: ^5.4.0
  chucker_flutter: ^1.8.5
  device_info_plus: ^11.4.0
  package_info_plus: ^8.3.0
  crypto: ^3.0.2
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env.dev
    - .env.release
    - assets/cert/cert.pem
